---
title: "4_AOU_validation"
author: "Joy_Fu"
date: "2023-05-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
lapply(paste('package:', names(sessionInfo()$otherPkgs), sep = ""),
       detach, character.only = TRUE, unload = TRUE)
pacman::p_load(tidyverse, h2o, epiflow, caret)
raw_data_path = "/Users/Mingzhou/Desktop/Projects/Dementia-prediction/data/"
output_path = "/Users/Mingzhou/Desktop/Projects/Dementia-prediction/output/"
# Source in useful functions
source("/Users/Mingzhou/Desktop/Projects/Dementia-prediction/code/functions.R")
```

# Part 1. AMR sample
## 1. AD trans-map PRS SNPs extraction
```{r}
load(file = paste0(raw_data_path, "prs/mod/AD_trans_beta_map.rda"))
load(file = paste0(raw_data_path, "prs/mod/AD_trans_map_EUR_1kg_mean.rda"))
load(file = paste0(raw_data_path, "prs/mod/AD_trans_map_EUR_1kg_sd.rda"))

# Output beta table - 
AD_trans_map_snp = AD_trans_beta_map %>% 
  select(rsid, beta_trans_map) %>% 
  separate(rsid, into = c("chr", "pos", "a0", "a1"), 
           sep = ":", remove = FALSE) %>% 
  mutate(pos_plus = as.character(as.numeric(pos) + 1)) %>% 
  mutate(output_var = paste0(chr, ":", pos, "-", pos_plus)) %>% 
  ungroup() %>% unique()
dim(AD_trans_map_snp) # (123,8)
write.table(AD_trans_map_snp, 
            file = paste0(output_path, "AOU_validation/AMR/AD_trans_map_snp.txt"),
            sep = "\t", quote = F, row.names = F, col.names = T)
```

## 2. Retrain models without PCs
```{r}
# Read in cleaned data
load(file = paste0(raw_data_path, "modeling/AMR/sample_AMR.rda"))
load(file = paste0(raw_data_path, "prs/mod/atlas_prs_final.rda"))
load(file = paste0(raw_data_path, "modeling/freeze60k_geno_beta_all_map.rda"))
prs_sample = sample_AMR %>% 
  mutate(UniqueSampleId = as.character(UniqueSampleId)) %>% 
  left_join(atlas_prs_final) %>% 
  select(-c(UniqueSampleId, gen_ancestry, record_length, 
            n_diagnosis, n_encounter,
            enc_per_yr, APOE, e2count)) %>% drop_na()
snp_map_sample = sample_AMR %>% 
  left_join(freeze60k_geno_beta_all_map) %>% 
  select(-c(UniqueSampleId, record_length, n_encounter, n_diagnosis, enc_per_yr)) 
```

```{r}
h2o.init(nthreads = -1)
seed_num = 20224766
Y = "dementia"

# Demographics only
target.train = as.h2o(prs_sample)
target.train[,Y] = as.factor(target.train[,Y])
X = c("age", "female")
demo.only = h2o.glm(training_frame = target.train, x = X, y = Y, 
                    balance_classes = T, model_id = "Demo only", 
                    nfolds = 5, fold_assignment = "Stratified",
                    seed = seed_num, family = "binomial", lambda = 0, 
                    standardize = T, keep_cross_validation_models = F)
# APOE only
X = c("e4count", "age", "female")
e4count = h2o.glm(training_frame = target.train, x = X, y = Y, 
                  balance_classes = T, model_id = "e4count", 
                  nfolds = 5, fold_assignment = "Stratified", 
                  seed = seed_num, family = "binomial", lambda = 0, 
                  standardize = T, keep_cross_validation_models = F)
# Best PRS (AD trans map)
X = c("AD_PRS_Trans_map", "age", "female")
PRS.trans.map = h2o.glm(training_frame = target.train, x = X, y = Y, 
                        balance_classes = T, model_id = "AD PRS Trans map", 
                        nfolds = 5, fold_assignment = "Stratified", 
                        seed = seed_num, family = "binomial", lambda = 0, 
                        standardize = T, keep_cross_validation_models = F)
# LASSO mapped SNPs
# Step 1: feature selection from LASSO interations
load(file = paste0(raw_data_path, "modeling/AMR/lasso_snp_allmap.rda"))
demo_set = c("age", "female", paste0('PC', 1:4))
# Get mapped SNPs
lasso_map_snp = selected_snp_summary_allmap %>% 
  arrange(desc(avg_percentage)) %>% 
  filter(freq >= 1000/ncol(freeze60k_geno_beta_all_map) & 
           (variable %!in% demo_set)) %>% 
  rowid_to_column(var = "rank_num") %>% 
  filter(freq >= 550 & avg_percentage >= 0.25)
dim(lasso_map_snp) # c(25,4)
selected_vars = lasso_map_snp$variable
# Step 2: fit LASSO (without PCs) with h2o model
target.train = as.h2o(snp_map_sample)
target.train[,Y] = as.factor(target.train[,Y])
X = c("age", "female", selected_vars)
allmap.nopc = h2o.glm(training_frame = target.train, x = X, y = Y, 
                      balance_classes = T, model_id = "LASSO SNPs (all map no PCs)", 
                      nfolds = 5, fold_assignment = "Stratified",  
                      seed = seed_num, family = "binomial", lambda = 0, 
                      standardize = T, keep_cross_validation_models = F)
```

```{r}
all_model_metric = c()
all_model_performance = c()
# Extract results
model_list = c("demo.only", "e4count", "PRS.trans.map", "allmap.nopc")
for (i in 1:length(model_list)) {
  print(paste0("Model: ", model_list[i]))
  # Run extraction function
  extract_cv = extract_cv_results(get(model_list[i]))
  model_metric = t(extract_cv[[1]]) %>% as.data.frame() %>% 
    mutate(mark = model_list[i])
  model_performance = extract_cv[[2]] %>% as.data.frame() %>% 
    mutate(mark = model_list[i])
  if (i == 1) {
    all_model_metric = model_metric
    all_model_performance = model_performance
  } else {
    all_model_metric = rbind(all_model_metric, model_metric)
    all_model_performance = rbind(all_model_performance, model_performance)
  }
}
# Join results together
nopc_model_metric = rbind(all_model_metric)
nopc_model_performance = rbind(all_model_performance)
nopc_model_summary = nopc_model_metric %>% inner_join(nopc_model_performance)
```

## 3. Outputs for AOU
### 1) Demo only
```{r}
coeff_table = demo.only@model$coefficients_table
write.table(coeff_table, 
            file = paste0(output_path, "AOU_validation/AMR/coeff_table_demo_AMR.txt"),
            sep = "\t", quote = F, row.names = F, col.names = T)
```

### 2) APOE
```{r}
coeff_table = e4count@model$coefficients_table
write.table(coeff_table, 
            file = paste0(output_path, "AOU_validation/AMR/coeff_table_APOE_AMR.txt"),
            sep = "\t", quote = F, row.names = F, col.names = T)
```

### 3) Best single AD PRS
```{r}
coeff_table = PRS.trans.map@model$coefficients_table
write.table(coeff_table, 
            file = paste0(output_path, "AOU_validation/AMR/coeff_table_ADPRS_AMR.txt"),
            sep = "\t", quote = F, row.names = F, col.names = T)
```

### 4) LASSO SNP model
```{r}
load(file = paste0(raw_data_path, "modeling/beta_merge_raw.rda"))
snp_beta_short = beta_merge_dbraw %>% rowwise() %>% 
  mutate(beta_AD_map = mean(c(beta_EUR_map, beta_AFR_map, beta_trans_map), na.rm = T)) %>% 
  mutate(beta_all_map = sum(c(beta_AD_map, beta_LBD_map, beta_PD_map, 
                              beta_PSP_map, beta_STROKE_map), na.rm = T)) %>% 
  select(rsid, beta_all_map)
# Output LASSO SNP beta table - 
lasso_map_snp_add = lasso_map_snp %>% 
  separate(variable, into = c("chr", "pos", "a0", "a1"), 
           sep = ":", remove = FALSE) %>% 
  mutate(pos_plus = as.character(as.numeric(pos) + 1)) %>% 
  mutate(output_var = paste0(chr, ":", pos, "-", pos_plus)) %>% ungroup() %>% 
  left_join(snp_beta_short, by = c("variable" = "rsid")) %>% 
  select(variable, chr, pos, a0, a1, output_var, beta_all_map) %>% unique()
dim(lasso_map_snp_add) # (25,7)
write.table(lasso_map_snp_add, 
            file = paste0(output_path, "AOU_validation/AMR/lasso_snp_AMR.txt"),
            sep = "\t", quote = F, row.names = F, col.names = T)
# Output LASSO SNP coefficient table
coeff_table = allmap.nopc@model$coefficients_table
save(coeff_table, file = paste0(raw_data_path, "modeling/AMR/coeff_table.rda"))
write.table(coeff_table, 
            file = paste0(output_path, "AOU_validation/AMR/coeff_table_lasso_AMR.txt"),
            sep = "\t", quote = F, row.names = F, col.names = T)
```

## 4. Selected SNPs exploration
```{r}
full_AD_trans = read.table(file = paste0(raw_data_path, "FUMA/FUMA_AD_trans/snps.txt"), 
                           header = T, sep = "\t", fill = T)
lasso_snp_info = liftover_full %>% 
  filter((chr_pos_name1 %in% lasso_map_snp_add$variable) | 
           (chr_pos_name2 %in% lasso_map_snp_add$variable)) %>% 
  select(rsID, chr, pos, phenotype) %>% dplyr::rename("rsid" = "rsID") %>% 
  unique() %>% arrange(chr, pos)
AD_trans_lead = lasso_snp_info %>% filter(phenotype == "AD_trans") %>% 
  select(rsid, chr, pos) %>% unique() # N = 9
write.table(AD_trans_lead, 
            file = paste0(output_path, "AOU_validation/AMR/FUMA_lead/AD_trans_lead.txt"),
            sep = "\t", quote = F, row.names = F, col.names = T)
AD_EUR_lead = lasso_snp_info %>% filter(phenotype == "AD_EUR") %>% 
  select(rsid, chr, pos) %>% unique() # N = 8
write.table(AD_EUR_lead, 
            file = paste0(output_path, "AOU_validation/AMR/FUMA_lead/AD_EUR_lead.txt"),
            sep = "\t", quote = F, row.names = F, col.names = T)
AD_AFR_lead = lasso_snp_info %>% filter(phenotype == "AD_AFR") %>% 
  select(rsid, chr, pos) %>% unique() # N = 5
write.table(AD_AFR_lead, 
            file = paste0(output_path, "AOU_validation/AMR/FUMA_lead/AD_AFR_lead.txt"),
            sep = "\t", quote = F, row.names = F, col.names = T)
PD_lead = lasso_snp_info %>% filter(phenotype == "PD") %>% 
  select(rsid, chr, pos) %>% unique() # N = 7
write.table(PD_lead, 
            file = paste0(output_path, "AOU_validation/AMR/FUMA_lead/PD_lead.txt"),
            sep = "\t", quote = F, row.names = F, col.names = T)
PSP_lead = lasso_snp_info %>% filter(phenotype == "PSP") %>% 
  select(rsid, chr, pos) %>% unique() # N = 3
write.table(PSP_lead, 
            file = paste0(output_path, "AOU_validation/AMR/FUMA_lead/PSP_lead.txt"),
            sep = "\t", quote = F, row.names = F, col.names = T)
STROKE_lead = lasso_snp_info %>% filter(phenotype == "STROKE") %>% 
  select(rsid, chr, pos) %>% unique() # N = 2
write.table(STROKE_lead, 
            file = paste0(output_path, "AOU_validation/AMR/FUMA_lead/STROKE_lead.txt"),
            sep = "\t", quote = F, row.names = F, col.names = T)
# No need to do LBD since the 2 SNPs for LBD are overlapped with others
```

```{r}
# Get back results from FUMA
new_AD_EUR = read.table(file = paste0(raw_data_path, "FUMA/with_lead_SNPs/AMR/AD_EUR/snps.txt"), 
                        header = T, sep = "\t", fill = T)
new_AD_EUR_short = new_AD_EUR %>% 
  select(rsID, CADD, nearestGene, dist, func, 
         posMapFilt, eqtlMapFilt, ciMapFilt) %>% 
  mutate(phenotype = "AD_EUR") %>% 
  right_join(lasso_snp_info, by = c("rsID" = "rsid", "phenotype")) %>% 
  filter(!is.na(CADD))
new_AD_AFR = read.table(file = paste0(raw_data_path, "FUMA/with_lead_SNPs/AMR/AD_AFR/snps.txt"), 
                        header = T, sep = "\t", fill = T)
new_AD_AFR_short = new_AD_AFR %>% 
  select(rsID, CADD, nearestGene, dist, func, 
         posMapFilt, eqtlMapFilt, ciMapFilt) %>% 
  mutate(phenotype = "AD_AFR") %>% 
  right_join(lasso_snp_info, by = c("rsID" = "rsid", "phenotype")) %>% 
  filter(!is.na(CADD))
new_AD_trans = read.table(file = paste0(raw_data_path, "FUMA/with_lead_SNPs/AMR/AD_trans/snps.txt"), 
                        header = T, sep = "\t", fill = T)
new_AD_trans_short = new_AD_trans %>% 
  select(rsID, CADD, nearestGene, dist, func, 
         posMapFilt, eqtlMapFilt, ciMapFilt) %>% 
  mutate(phenotype = "AD_trans") %>% 
  right_join(lasso_snp_info, by = c("rsID" = "rsid", "phenotype")) %>% 
  filter(!is.na(CADD))
new_PD = read.table(file = paste0(raw_data_path, "FUMA/with_lead_SNPs/AMR/PD/snps.txt"), 
                    header = T, sep = "\t", fill = T)
new_PD_short = new_PD %>% 
  select(rsID, CADD, nearestGene, dist, func, 
         posMapFilt, eqtlMapFilt, ciMapFilt) %>% 
  mutate(phenotype = "PD") %>% 
  right_join(lasso_snp_info, by = c("rsID" = "rsid", "phenotype")) %>% 
  filter(!is.na(CADD))
new_PSP = read.table(file = paste0(raw_data_path, "FUMA/with_lead_SNPs/AMR/PSP/snps.txt"), 
                     header = T, sep = "\t", fill = T)
new_PSP_short = new_PSP %>% 
  select(rsID, CADD, nearestGene, dist, func, 
         posMapFilt, eqtlMapFilt, ciMapFilt) %>% 
  mutate(phenotype = "PSP") %>% 
  right_join(lasso_snp_info, by = c("rsID" = "rsid", "phenotype")) %>% 
  filter(!is.na(CADD))
new_STROKE = read.table(file = paste0(raw_data_path, "FUMA/with_lead_SNPs/AMR/STROKE/snps.txt"), 
                        header = T, sep = "\t", fill = T)
new_STROKE_short = new_STROKE %>% 
  select(rsID, CADD, nearestGene, dist, func, 
         posMapFilt, eqtlMapFilt, ciMapFilt) %>% 
  mutate(phenotype = "STROKE") %>% 
  right_join(lasso_snp_info, by = c("rsID" = "rsid", "phenotype")) %>% 
  filter(!is.na(CADD))

candidate_snps_info = rbind(new_AD_EUR_short, new_AD_AFR_short, new_AD_trans_short,
                            new_PD_short, new_PSP_short, new_STROKE_short) %>% 
  as.data.frame() %>% right_join(lasso_snp_info) %>% unique() %>% select(-rsid)
save(candidate_snps_info, file = paste0(raw_data_path, "modeling/AMR/candidate_snps_info.rda"))
write.table(candidate_snps_info, 
            file = paste0(output_path, "AOU_validation/AMR/FUMA_lead/candidate_snps_info.txt"),
            sep = "\t", quote = F, row.names = F, col.names = T)
```


```{r}

```



```{r}
  select(rsID, nearestGene, dist, func, posMapFilt, eqtlMapFilt, ciMapFilt)
rsID_check_AD = mapped_snp %>% 
  
  filter(uniqueID %in% c(snps_either, snps_AD_specific, snps_epi_specific)) %>% 
  select(rsID, uniqueID, chr, pos, a0, a1, gwasP, CADD, phenotype)

lasso_map_snp_short = lasso_map_snp_add
```


# Part 2. AFR sample
## 1. AD trans-map PRS SNPs extraction
```{r}
load(file = paste0(raw_data_path, "prs/mod/AD_trans_beta_indsig.rda"))
load(file = paste0(raw_data_path, "prs/mod/AD_trans_indsig_EUR_1kg_mean.rda"))
load(file = paste0(raw_data_path, "prs/mod/AD_trans_indsig_EUR_1kg_sd.rda"))

# Output beta table - 
AD_trans_indsig_snp = AD_trans_beta_indsig %>% 
  select(rsid, beta_trans_map) %>% 
  separate(rsid, into = c("chr", "pos", "a0", "a1"), 
           sep = ":", remove = FALSE) %>% 
  mutate(pos_plus = as.character(as.numeric(pos) + 1)) %>% 
  mutate(output_var = paste0(chr, ":", pos, "-", pos_plus)) %>% 
  ungroup() %>% unique()
dim(AD_trans_map_snp) # (123,8)
write.table(AD_trans_map_snp, 
            file = paste0(output_path, "AOU_validation/AMR/AD_trans_map_snp.txt"),
            sep = "\t", quote = F, row.names = F, col.names = T)
```


