---
title: "5_Interpretation"
author: "Joy_Fu"
date: "2023-06-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
# lapply(paste('package:', names(sessionInfo()$otherPkgs), sep = ""),
#        detach, character.only = TRUE, unload = TRUE)
pacman::p_load(tidyverse, epiflow)
raw_data_path = "/Users/Mingzhou/Desktop/Projects/Dementia-prediction/data/"
output_path = "/Users/Mingzhou/Desktop/Projects/Dementia-prediction/output/"
# Source in useful functions
source("/Users/Mingzhou/Desktop/Projects/Dementia-prediction/code/functions.R")
```


# Part 1. Selected SNPs
```{r}
# Load general information
load(file = paste0(raw_data_path, "modeling/beta_merge_raw.rda"))
load(file = paste0(raw_data_path, "FUMA/liftover_full.rda"))
load(file = paste0(raw_data_path, "Interpretation/info_tbl/gene_info_full.rda"))
load(file = paste0(raw_data_path, "Interpretation/info_tbl/snp_info_full.rda"))
load(file = paste0(raw_data_path, "Interpretation/info_tbl/snp_info_combine.rda"))
# Load selected SNPs
# load(file = paste0(raw_data_path, "Interpretation/snps_AMR_all_map.rda"))
# load(file = paste0(raw_data_path, "Interpretation/snps_AFR_all_map.rda"))
load(file = paste0(raw_data_path, "Interpretation/snps_EAS_all_map.rda"))
# Read in all eqtl/ci data
source("/Users/Mingzhou/Desktop/Projects/Dementia-prediction/code/read_FUMA.R")

gene_info_short = gene_info_full %>% 
  select(ensg, symbol, chr, start, end, type) %>% unique()
```

## AMR results
### 1. SNP info
```{r}
amr_snps = beta_merge_raw %>% filter(rsid %in% snps_AMR_all_map) %>% 
  select(rsid, chr, pos, a0, a1, beta_EUR_map, beta_AFR_map, beta_trans_map, 
         beta_LBD_map, beta_PD_map, beta_PSP_map, beta_STROKE_map)

amr_snps_info = liftover_full %>% 
  filter((chr_pos_name1 %in% amr_snps$rsid) | 
           (chr_pos_name2 %in% amr_snps$rsid)) %>% 
  select(rsID, chr, pos) %>% unique() %>% full_join(amr_snps) %>% 
  mutate(AD_EUR = if_else(!is.na(beta_EUR_map), 1, NA),
         AD_AFR = if_else(!is.na(beta_AFR_map), 1, NA),
         AD_Trans = if_else(!is.na(beta_trans_map), 1, NA),
         LBD = if_else(!is.na(beta_LBD_map), 1, NA),
         PD = if_else(!is.na(beta_PD_map), 1, NA),
         PSP = if_else(!is.na(beta_PSP_map), 1, NA),
         STROKE = if_else(!is.na(beta_STROKE_map), 1, NA)) %>% 
  select(rsID, AD_EUR, AD_AFR, AD_Trans, LBD, PD, PSP, LBD, STROKE,
         chr, pos) %>% left_join(snp_info_full) %>% arrange(chr, pos)
write.table(amr_snps_info, 
            file = paste0(output_path, "interpretation/amr_snps_info.txt"),
            sep = "\t", quote = F, row.names = F, col.names = T)
```

### 2. Mapped genes
```{r}
pos_map = amr_snps_info %>% group_by(nearestGene) %>% summarise(n_pos = n()) 
pos_map_genes = pos_map %>% select(nearestGene) %>% unique() %>% 
  mutate(positional = "Yes") %>% dplyr::rename("symbol" = "nearestGene")
```

```{r}
eqtl_map_pre = amr_snps_info %>% filter(eqtlMapFilt == 1) %>% 
  left_join(snp_info_combine) %>% 
  select(uniqID, rsID, AD_EUR, AD_AFR, AD_Trans, LBD, PD, PSP, LBD, STROKE)
eqtl_EUR_map = eqtl_map_pre %>% filter(AD_EUR == 1) %>% left_join(eqtl_EUR)
eqtl_trans_map = eqtl_map_pre %>% filter(AD_Trans == 1) %>% left_join(eqtl_Trans)
eqtl_PD_map = eqtl_map_pre %>% filter(PD == 1) %>% left_join(eqtl_PD)
eqtl_PSP_map = eqtl_map_pre %>% filter(PSP == 1) %>% left_join(eqtl_PSP)

eqtl_map = rbind(eqtl_EUR_map, eqtl_trans_map, eqtl_PD_map, eqtl_PSP_map) %>% unique()
eqtl_map_genes = eqtl_map %>% select(symbol, alignedDirection) %>% 
  mutate(eqtl_pre = "Yes",
         eqtl = paste0(eqtl_pre, " (", alignedDirection, ")")) %>% 
  select(symbol, eqtl) %>% unique()
```

```{r}
ci_map_pre = amr_snps_info %>% filter(ciMapFilt == 1)
ci_EUR_rsid = ci_map_pre %>% filter(AD_EUR == 1) %>% pull(rsID)
ci_EUR_genes = AD_EUR_ci %>% 
  filter(sapply(strsplit(SNPs, ";"), 
                function(x) any(x %in% ci_EUR_rsid))) %>% 
  select(genes) %>% drop_na() %>% unique()
ci_AFR_rsid = ci_map_pre %>% filter(AD_AFR == 1) %>% pull(rsID)
ci_AFR_genes = AD_AFR_ci %>% 
  filter(sapply(strsplit(SNPs, ";"), 
                function(x) any(x %in% ci_AFR_rsid))) %>% 
  select(genes) %>% drop_na() %>% unique()
ci_trans_rsid = ci_map_pre %>% filter(AD_Trans == 1) %>% pull(rsID)
ci_trans_genes = AD_trans_ci %>% 
  filter(sapply(strsplit(SNPs, ";"), 
                function(x) any(x %in% ci_trans_rsid))) %>% 
  select(genes) %>% drop_na() %>% unique()
ci_PD_rsid = ci_map_pre %>% filter(PD == 1) %>% pull(rsID)
ci_PD_genes = PD_ci %>% 
  filter(sapply(strsplit(SNPs, ";"), 
                function(x) any(x %in% ci_PD_rsid))) %>% 
  select(genes) %>% drop_na() %>% unique()
ci_PSP_rsid = ci_map_pre %>% filter(PSP == 1) %>% pull(rsID)
ci_PSP_genes = PSP_ci %>% 
  filter(sapply(strsplit(SNPs, ";"), 
                function(x) any(x %in% ci_PSP_rsid))) %>% 
  select(genes) %>% drop_na() %>% unique()
ci_LBD_rsid = ci_map_pre %>% filter(LBD == 1) %>% pull(rsID)
ci_LBD_genes = LBD_ci %>% 
  filter(sapply(strsplit(SNPs, ";"), 
                function(x) any(x %in% ci_LBD_rsid))) %>% 
  select(genes) %>% drop_na() %>% unique()

ci_map_full = rbind(ci_EUR_genes, ci_AFR_genes, ci_trans_genes, ci_PD_genes,
                    ci_PSP_genes, ci_LBD_genes) %>% unique()
ci_map_genes = ci_map_full %>% 
  left_join(gene_info_short, by = c("genes" = "ensg")) %>% unique() %>% drop_na() %>% 
  select(symbol) %>% unique() %>% mutate(ci = "Yes") %>% 
  filter(symbol != "Y_RNA")
```

```{r}
# combine together
amr_genes_info = pos_map_genes %>% full_join(eqtl_map_genes) %>% 
  full_join(ci_map_genes) %>% 
  left_join(gene_info_short) %>% filter(!is.na(ensg)) %>% 
  replace_na(list(positional = "No", eqtl = "No", ci = "No")) %>% 
  arrange(chr, start)
write.table(amr_genes_info, 
            file = paste0(output_path, "interpretation/amr_genes_info.txt"),
            sep = "\t", quote = F, row.names = F, col.names = T)
```


## AFR results
### 1. SNP info
```{r}
afr_snps = beta_merge_raw %>% filter(rsid %in% snps_AFR_all_map) %>% 
  select(rsid, chr, pos, a0, a1, beta_EUR_map, beta_AFR_map, beta_trans_map, 
         beta_LBD_map, beta_PD_map, beta_PSP_map, beta_STROKE_map)

afr_snps_info = liftover_full %>% 
  filter((chr_pos_name1 %in% afr_snps$rsid) | 
           (chr_pos_name2 %in% afr_snps$rsid)) %>% 
  select(rsID, chr, pos) %>% unique() %>% full_join(afr_snps) %>% 
  mutate(AD_EUR = if_else(!is.na(beta_EUR_map), 1, NA),
         AD_AFR = if_else(!is.na(beta_AFR_map), 1, NA),
         AD_Trans = if_else(!is.na(beta_trans_map), 1, NA),
         LBD = if_else(!is.na(beta_LBD_map), 1, NA),
         PD = if_else(!is.na(beta_PD_map), 1, NA),
         PSP = if_else(!is.na(beta_PSP_map), 1, NA),
         STROKE = if_else(!is.na(beta_STROKE_map), 1, NA)) %>% 
  select(rsID, AD_EUR, AD_AFR, AD_Trans, LBD, PD, PSP, LBD, STROKE,
         chr, pos) %>% left_join(snp_info_full) %>% arrange(chr, pos)
write.table(afr_snps_info, 
            file = paste0(output_path, "interpretation/afr_snps_info.txt"),
            sep = "\t", quote = F, row.names = F, col.names = T)
```

### 2. Mapped genes
```{r}
pos_map = afr_snps_info %>% group_by(nearestGene) %>% summarise(n_pos = n()) 
pos_map_genes = pos_map %>% select(nearestGene) %>% unique() %>% 
  mutate(positional = "Yes") %>% dplyr::rename("symbol" = "nearestGene")
```

```{r}
eqtl_map_pre = afr_snps_info %>% filter(eqtlMapFilt == 1) %>% 
  left_join(snp_info_combine) %>% 
  select(uniqID, rsID, AD_EUR, AD_AFR, AD_Trans, LBD, PD, PSP, LBD, STROKE)
eqtl_EUR_map = eqtl_map_pre %>% filter(AD_EUR == 1) %>% left_join(eqtl_EUR)
eqtl_trans_map = eqtl_map_pre %>% filter(AD_Trans == 1) %>% left_join(eqtl_Trans)
eqtl_LBD_map = eqtl_map_pre %>% filter(LBD == 1) %>% left_join(eqtl_LBD)
eqtl_PD_map = eqtl_map_pre %>% filter(PD == 1) %>% left_join(eqtl_PD)
eqtl_PSP_map = eqtl_map_pre %>% filter(PSP == 1) %>% left_join(eqtl_PSP)

eqtl_map = rbind(eqtl_EUR_map, eqtl_trans_map, eqtl_LBD_map, eqtl_PD_map, eqtl_PSP_map) %>% unique()
eqtl_map_genes = eqtl_map %>% select(symbol, alignedDirection) %>% 
  mutate(eqtl_pre = "Yes",
         eqtl = paste0(eqtl_pre, " (", alignedDirection, ")")) %>% 
  select(symbol, eqtl) %>% unique()
```

```{r}
ci_map_pre = afr_snps_info %>% filter(ciMapFilt == 1)
ci_EUR_rsid = ci_map_pre %>% filter(AD_EUR == 1) %>% pull(rsID)
ci_EUR_genes = AD_EUR_ci %>% 
  filter(sapply(strsplit(SNPs, ";"), 
                function(x) any(x %in% ci_EUR_rsid))) %>% 
  select(genes) %>% drop_na() %>% unique()
ci_AFR_rsid = ci_map_pre %>% filter(AD_AFR == 1) %>% pull(rsID)
ci_AFR_genes = AD_AFR_ci %>% 
  filter(sapply(strsplit(SNPs, ";"), 
                function(x) any(x %in% ci_AFR_rsid))) %>% 
  select(genes) %>% drop_na() %>% unique()
ci_trans_rsid = ci_map_pre %>% filter(AD_Trans == 1) %>% pull(rsID)
ci_trans_genes = AD_trans_ci %>% 
  filter(sapply(strsplit(SNPs, ";"), 
                function(x) any(x %in% ci_trans_rsid))) %>% 
  select(genes) %>% drop_na() %>% unique()
ci_PD_rsid = ci_map_pre %>% filter(PD == 1) %>% pull(rsID)
ci_PD_genes = PD_ci %>% 
  filter(sapply(strsplit(SNPs, ";"), 
                function(x) any(x %in% ci_PD_rsid))) %>% 
  select(genes) %>% drop_na() %>% unique()
ci_PSP_rsid = ci_map_pre %>% filter(PSP == 1) %>% pull(rsID)
ci_PSP_genes = PSP_ci %>% 
  filter(sapply(strsplit(SNPs, ";"), 
                function(x) any(x %in% ci_PSP_rsid))) %>% 
  select(genes) %>% drop_na() %>% unique()
ci_LBD_rsid = ci_map_pre %>% filter(LBD == 1) %>% pull(rsID)
ci_LBD_genes = LBD_ci %>% 
  filter(sapply(strsplit(SNPs, ";"), 
                function(x) any(x %in% ci_LBD_rsid))) %>% 
  select(genes) %>% drop_na() %>% unique()

ci_map_full = rbind(ci_EUR_genes, ci_AFR_genes, ci_trans_genes, ci_PD_genes,
                    ci_PSP_genes, ci_LBD_genes) %>% unique()
ci_map_genes = ci_map_full %>% 
  left_join(gene_info_short, by = c("genes" = "ensg")) %>% unique() %>% drop_na() %>% 
  select(symbol) %>% unique() %>% mutate(ci = "Yes") %>% 
  filter(symbol != "Y_RNA")
```

```{r}
# combine together
afr_genes_info = pos_map_genes %>% full_join(eqtl_map_genes) %>% 
  full_join(ci_map_genes) %>% 
  left_join(gene_info_short) %>% filter(!is.na(ensg)) %>% 
  replace_na(list(positional = "No", eqtl = "No", ci = "No")) %>% 
  arrange(chr, start)
write.table(afr_genes_info, 
            file = paste0(output_path, "interpretation/afr_genes_info.txt"),
            sep = "\t", quote = F, row.names = F, col.names = T)
```


## EAS results
### 1. SNP info
```{r}
eas_snps = beta_merge_raw %>% filter(rsid %in% snps_EAS_all_map) %>% 
  select(rsid, chr, pos, a0, a1, beta_EUR_map, beta_AFR_map, beta_trans_map, 
         beta_LBD_map, beta_PD_map, beta_PSP_map, beta_STROKE_map)

eas_snps_info = liftover_full %>% 
  filter((chr_pos_name1 %in% eas_snps$rsid) | 
           (chr_pos_name2 %in% eas_snps$rsid)) %>% 
  select(rsID, chr, pos) %>% unique() %>% full_join(eas_snps) %>% 
  mutate(AD_EUR = if_else(!is.na(beta_EUR_map), 1, NA),
         AD_AFR = if_else(!is.na(beta_AFR_map), 1, NA),
         AD_Trans = if_else(!is.na(beta_trans_map), 1, NA),
         LBD = if_else(!is.na(beta_LBD_map), 1, NA),
         PD = if_else(!is.na(beta_PD_map), 1, NA),
         PSP = if_else(!is.na(beta_PSP_map), 1, NA),
         STROKE = if_else(!is.na(beta_STROKE_map), 1, NA)) %>% 
  select(rsID, AD_EUR, AD_AFR, AD_Trans, LBD, PD, PSP, LBD, STROKE,
         chr, pos) %>% left_join(snp_info_full) %>% arrange(chr, pos)
write.table(eas_snps_info, 
            file = paste0(output_path, "interpretation/eas_snps_info.txt"),
            sep = "\t", quote = F, row.names = F, col.names = T)
```

### 2. Mapped genes
```{r}
pos_map = eas_snps_info %>% group_by(nearestGene) %>% summarise(n_pos = n()) 
pos_map_genes = pos_map %>% select(nearestGene) %>% unique() %>% 
  mutate(positional = "Yes") %>% dplyr::rename("symbol" = "nearestGene")
```

```{r}
eqtl_map_pre = eas_snps_info %>% filter(eqtlMapFilt == 1) %>% 
  left_join(snp_info_combine) %>% 
  select(uniqID, rsID, AD_EUR, AD_AFR, AD_Trans, LBD, PD, PSP, LBD, STROKE)
eqtl_EUR_map = eqtl_map_pre %>% filter(AD_EUR == 1) %>% left_join(eqtl_EUR)
eqtl_trans_map = eqtl_map_pre %>% filter(AD_Trans == 1) %>% left_join(eqtl_Trans)
eqtl_PD_map = eqtl_map_pre %>% filter(PD == 1) %>% left_join(eqtl_PD)
eqtl_PSP_map = eqtl_map_pre %>% filter(PSP == 1) %>% left_join(eqtl_PSP)

eqtl_map = rbind(eqtl_EUR_map, eqtl_trans_map, eqtl_PD_map, eqtl_PSP_map) %>% unique()
eqtl_map_genes = eqtl_map %>% select(symbol, alignedDirection) %>% 
  mutate(eqtl_pre = "Yes",
         eqtl = paste0(eqtl_pre, " (", alignedDirection, ")")) %>% 
  select(symbol, eqtl) %>% unique()
```

```{r}
ci_map_pre = eas_snps_info %>% filter(ciMapFilt == 1)
ci_EUR_rsid = ci_map_pre %>% filter(AD_EUR == 1) %>% pull(rsID)
ci_EUR_genes = AD_EUR_ci %>% 
  filter(sapply(strsplit(SNPs, ";"), 
                function(x) any(x %in% ci_EUR_rsid))) %>% 
  select(genes) %>% drop_na() %>% unique()
ci_AFR_rsid = ci_map_pre %>% filter(AD_AFR == 1) %>% pull(rsID)
ci_AFR_genes = AD_AFR_ci %>% 
  filter(sapply(strsplit(SNPs, ";"), 
                function(x) any(x %in% ci_AFR_rsid))) %>% 
  select(genes) %>% drop_na() %>% unique()
ci_trans_rsid = ci_map_pre %>% filter(AD_Trans == 1) %>% pull(rsID)
ci_trans_genes = AD_trans_ci %>% 
  filter(sapply(strsplit(SNPs, ";"), 
                function(x) any(x %in% ci_trans_rsid))) %>% 
  select(genes) %>% drop_na() %>% unique()
ci_PD_rsid = ci_map_pre %>% filter(PD == 1) %>% pull(rsID)
ci_PD_genes = PD_ci %>% 
  filter(sapply(strsplit(SNPs, ";"), 
                function(x) any(x %in% ci_PD_rsid))) %>% 
  select(genes) %>% drop_na() %>% unique()
ci_PSP_rsid = ci_map_pre %>% filter(PSP == 1) %>% pull(rsID)
ci_PSP_genes = PSP_ci %>% 
  filter(sapply(strsplit(SNPs, ";"), 
                function(x) any(x %in% ci_PSP_rsid))) %>% 
  select(genes) %>% drop_na() %>% unique()
ci_LBD_rsid = ci_map_pre %>% filter(LBD == 1) %>% pull(rsID)
ci_LBD_genes = LBD_ci %>% 
  filter(sapply(strsplit(SNPs, ";"), 
                function(x) any(x %in% ci_LBD_rsid))) %>% 
  select(genes) %>% drop_na() %>% unique()
ci_STROKE_rsid = ci_map_pre %>% filter(STROKE == 1) %>% pull(rsID)
ci_STROKE_genes = STROKE_ci %>% 
  filter(sapply(strsplit(SNPs, ";"), 
                function(x) any(x %in% ci_STROKE_rsid))) %>% 
  select(genes) %>% drop_na() %>% unique()

ci_map_full = rbind(ci_EUR_genes, ci_AFR_genes, ci_trans_genes, ci_PD_genes,
                    ci_PSP_genes, ci_LBD_genes, ci_STROKE_genes) %>% unique()
ci_map_genes = ci_map_full %>% 
  left_join(gene_info_short, by = c("genes" = "ensg")) %>% unique() %>% drop_na() %>% 
  select(symbol) %>% unique() %>% mutate(ci = "Yes") %>% 
  filter(symbol != "Y_RNA")
```

```{r}
# combine together
eas_genes_info = pos_map_genes %>% full_join(eqtl_map_genes) %>% 
  full_join(ci_map_genes) %>% 
  left_join(gene_info_short) %>% filter(!is.na(ensg)) %>% 
  replace_na(list(positional = "No", eqtl = "No", ci = "No")) %>% 
  arrange(chr, start)
write.table(eas_genes_info, 
            file = paste0(output_path, "interpretation/eas_genes_info.txt"),
            sep = "\t", quote = F, row.names = F, col.names = T)
```

# Part 2. Overlaps
```{r}
# load gene combined df (this df was created in Sup2_figures.Rmd)
load(file = paste0(output_path, "interpretation/genes_df_combined.rda"))
AMR_gene = read.table(file = paste0(output_path, "interpretation/amr_genes_info.txt"), 
                      header = T, sep = "\t", fill = T)
AFR_gene = read.table(file = paste0(output_path, "interpretation/afr_genes_info.txt"), 
                      header = T, sep = "\t", fill = T)
EAS_gene = read.table(file = paste0(output_path, "interpretation/eas_genes_info.txt"), 
                      header = T, sep = "\t", fill = T)
```

```{r}
overlap_all = genes_df_combined %>% 
  filter(AMR_specific == 1 & AFR_specific == 1 & EAS_specific == 1) %>% 
  left_join(AMR_gene)
# N = 13 overlap
overlap_all %>% pull(symbol) %>% paste(collapse = ", ")
```

```{r}
amr_afr = genes_df_combined %>% 
  filter(AMR_specific == 1 & AFR_specific == 1 & EAS_specific == 0) %>% 
  left_join(AMR_gene)
amr_afr %>% pull(symbol) %>% paste(collapse = ", ")
```

```{r}
amr_eas = genes_df_combined %>% 
  filter(AMR_specific == 1 & AFR_specific == 0 & EAS_specific == 1) %>% 
  left_join(AMR_gene)
amr_eas %>% pull(symbol) %>% paste(collapse = ", ")
```

```{r}
afr_eas = genes_df_combined %>% 
  filter(AMR_specific == 0 & AFR_specific == 1 & EAS_specific == 1) %>% 
  left_join(AFR_gene)
afr_eas %>% pull(symbol) %>% paste(collapse = ", ")
```

```{r}
eas_specific = genes_df_combined %>% 
  filter(AMR_specific == 0 & AFR_specific == 0 & EAS_specific == 1) %>% 
  left_join(EAS_gene)
eas_specific %>% pull(symbol) %>% paste(collapse = ", ")
```

```{r}
afr_specific = genes_df_combined %>% 
  filter(AMR_specific == 0 & AFR_specific == 1 & EAS_specific == 0) %>% 
  left_join(AFR_gene)
afr_specific %>% pull(symbol) %>% paste(collapse = ", ")
```

```{r}
amr_specific = genes_df_combined %>% 
  filter(AMR_specific == 1 & AFR_specific == 0 & EAS_specific == 0) %>% 
  left_join(AMR_gene)
amr_specific %>% pull(symbol) %>% paste(collapse = ", ")
```

