---
title: "5_figures"
author: "Joy_Fu"
date: "2023-05-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
pacman::p_load(tidyverse, fmsb, UpSetR)
raw_data_path = "/Users/Mingzhou/Desktop/Projects/Dementia-prediction/data/"
output_path = "/Users/Mingzhou/Desktop/Projects/Dementia-prediction/output/"
# Source in useful functions
source("/Users/Mingzhou/Desktop/Projects/Dementia-prediction/code/functions.R")
```

# Part 1. Donut plot
```{r}
load(file = paste0(raw_data_path, "atlas/pheno/mod/enc_demo_map.rda"))
# Dementia cases info
dem_phecode = c("290.1", "290.11", "290.12", "290.13", "290.16")
dem_icds = c("F01", "F01.5", "F01.50", "F01.51", "F01.511", "F01.518",
             "F02.80", "F02.81", "F02.811", "F02.818", 
             "F03", "F03.9", "F03.90", "F03.91", "F03.911", "F03.918",
             "G30", "G30.0", "G30.1", "G30.8", "G30.9",
             "G31.0", "G31.01", "G31.09", "G31.1", "G31.83", "G31.85", 
             "G23.1")
dem_case_info = enc_demo_map %>% 
  # select cases only
  filter(phecode %in% dem_phecode | DiagnosisCode %in% dem_icds) %>% 
  mutate(ICD_3digit = substr(DiagnosisCode, 1, 3)) %>% 
  select(UniqueSampleId, ICD_3digit) %>% unique()
```

## 1. AMR
```{r}
load(file = paste0(raw_data_path, "modeling/AMR/sample_AMR_final.rda"))
case_AMR = dem_case_info %>% 
  filter(UniqueSampleId %in% sample_AMR_final$UniqueSampleId) %>% 
  mutate(value = 1) %>% 
  spread(key = "ICD_3digit", value = "value") %>% 
  mutate(final_diagnosis = case_when(
    !is.na(G30) ~ "G30",
    !is.na(F01) ~ "F01",
    !is.na(G31) ~ "G31",
    !is.na(F02) ~ "F02",
    !is.na(F03) ~ "F03"
  )) %>% column_to_rownames(var = "UniqueSampleId")

data_plot = table(case_AMR$final_diagnosis) %>% t() %>% as.data.frame() %>% 
  select(-Var1) %>% mutate(Freq = as.numeric(Freq))
names(data_plot) = c("category", "count")
# Compute percentages
data_plot_add = data_plot %>% 
  mutate(fraction = count/sum(count),
         ymax = cumsum(fraction),
         ymin = c(0, head(ymax, n = -1)),
         labelPosition = (ymax + ymin)/2,
         label = paste0(category, "\n count: ", count))
# Make the plot
pdf(paste0(output_path, "donut_AMR.pdf"), width = 6, height = 5)
ggplot(data_plot_add, 
       aes(ymax = ymax, ymin = ymin, xmax = 4, xmin = 3, fill = category)) +
  geom_rect() + 
  geom_text(x = 2, aes(y = labelPosition, label = label, color = category), size = 4) +
  scale_fill_brewer(palette = "Set2") +
  scale_color_brewer(palette = "Set2") +
  coord_polar(theta = "y") +
  xlim(c(-1, 4)) +
  theme_void() +
  theme(legend.position = "none")
dev.off()
```

## 2. AFR
```{r}
load(file = paste0(raw_data_path, "modeling/AFR/sample_AFR_final.rda"))
case_AFR = dem_case_info %>% 
  filter(UniqueSampleId %in% sample_AFR_final$UniqueSampleId) %>% 
  mutate(value = 1) %>% 
  spread(key = "ICD_3digit", value = "value") %>% 
  mutate(final_diagnosis = case_when(
    !is.na(G30) ~ "G30",
    !is.na(F01) ~ "F01",
    !is.na(G31) ~ "G31",
    !is.na(F02) ~ "F02",
    !is.na(F03) ~ "F03"
  )) %>% column_to_rownames(var = "UniqueSampleId")

data_plot = table(case_AFR$final_diagnosis) %>% t() %>% as.data.frame() %>% 
  select(-Var1) %>% mutate(Freq = as.numeric(Freq))
names(data_plot) = c("category", "count")
# Compute percentages
data_plot_add = data_plot %>% 
  mutate(fraction = count/sum(count),
         ymax = cumsum(fraction),
         ymin = c(0, head(ymax, n = -1)),
         labelPosition = (ymax + ymin)/2,
         label = paste0(category, "\n count: ", count))
# Make the plot
pdf(paste0(output_path, "donut_AFR.pdf"), width = 6, height = 5)
ggplot(data_plot_add, 
       aes(ymax = ymax, ymin = ymin, xmax = 4, xmin = 3, fill = category)) +
  geom_rect() + 
  geom_text(x = 2, aes(y = labelPosition, label = label, color = category), size = 4) +
  scale_fill_brewer(palette = "Set2") +
  scale_color_brewer(palette = "Set2") +
  coord_polar(theta = "y") +
  xlim(c(-1, 4)) +
  theme_void() +
  theme(legend.position = "none")
dev.off()
```

## 3. EAS
```{r}
load(file = paste0(raw_data_path, "modeling/EAS/sample_EAS_final.rda"))
case_EAS = dem_case_info %>% 
  filter(UniqueSampleId %in% sample_EAS_final$UniqueSampleId) %>% 
  mutate(value = 1) %>% 
  spread(key = "ICD_3digit", value = "value") %>% 
  mutate(final_diagnosis = case_when(
    !is.na(G30) ~ "G30",
    !is.na(F01) ~ "F01",
    !is.na(G31) ~ "G31",
    !is.na(F02) ~ "F02",
    !is.na(F03) ~ "F03"
  )) %>% column_to_rownames(var = "UniqueSampleId")

data_plot = table(case_EAS$final_diagnosis) %>% t() %>% as.data.frame() %>% 
  select(-Var1) %>% mutate(Freq = as.numeric(Freq))
names(data_plot) = c("category", "count")
# Compute percentages
data_plot_add = data_plot %>% 
  mutate(fraction = count/sum(count),
         ymax = cumsum(fraction),
         ymin = c(0, head(ymax, n = -1)),
         labelPosition = (ymax + ymin)/2,
         label = paste0(category, "\n count: ", count))
# Make the plot
pdf(paste0(output_path, "donut_EAS.pdf"), width = 6, height = 5)
ggplot(data_plot_add, 
       aes(ymax = ymax, ymin = ymin, xmax = 4, xmin = 3, fill = category)) +
  geom_rect() + 
  geom_text(x = 2, aes(y = labelPosition, label = label, color = category), size = 4) +
  scale_fill_brewer(palette = "Set2") +
  scale_color_brewer(palette = "Set2") +
  coord_polar(theta = "y") +
  xlim(c(-1, 4)) +
  theme_void() +
  theme(legend.position = "none")
dev.off()
```


# Part 2. Radar plot
```{r}
# plot setups - Color vector
colors_border = c(rgb(0.2,0.5,0.5,0.9), 
                  rgb(0.8,0.2,0.5,0.9), 
                  rgb(0.7,0.5,0.1,0.9))
colors_in = c(rgb(0.2,0.5,0.5,0.4), 
              rgb(0.8,0.2,0.5,0.4), 
              rgb(0.7,0.5,0.1,0.4))
```

## 1. AUPRC
```{r}
# Create data: note in High school for several students
amr_score = c(0.1620, 0.1872, 0.1908, 0.1884, 0.2769)
afr_score = c(0.1372, 0.1516, 0.1421, 0.1457, 0.2818)
eas_score = c(0.1958, 0.2419, 0.2115, 0.2555, 0.3883)
plot_auprc = as.data.frame(rbind(amr_score, afr_score, eas_score))
colnames(plot_auprc) = c("Demographics", "APOE", "Best_single_PRS", 
                         "Best_multiple_PRS", "LASSO_neuro_map")
rownames(plot_auprc) = c("AMR", "AFR", "EAS")
plot_auprc = rbind(rep(0.4, 5), rep(0.1, 5), plot_auprc)

pdf(paste0(output_path, "AUPRC_radar.pdf"), width = 8, height = 8)
radarchart(plot_auprc, axistype = 1 , maxmin = TRUE,
           #custom polygon
           pcol = colors_border, pfcol = colors_in, plwd = 3, plty = 1,
           #custom the grid
           cglcol = "grey", cglty = 1, axislabcol = "black", 
           caxislabels = seq(0.1, 0.4, 0.075), cglwd = 0.8,
           #custom labels
           vlcex = 0.9)
legend(x = 0.8, y = 1, legend = rownames(plot_auprc[-c(1,2),]), bty = "n", 
       pch = 20 , col = colors_in , text.col = "black", cex = 1, pt.cex = 2)
dev.off()
```

## 2. AUROC
```{r}
amr_score = c(0.7506, 0.7525, 0.7577, 0.7571, 0.7994)
afr_score = c(0.7058, 0.7113, 0.6996, 0.7163, 0.7810)
eas_score = c(0.7704, 0.7835, 0.7717, 0.7963, 0.8682)
plot_auc = as.data.frame(rbind(amr_score, afr_score, eas_score))
colnames(plot_auc) = c("Demographics", "APOE", "Best_single_PRS", 
                       "Best_multiple_PRS", "LASSO_neuro_map")
rownames(plot_auc) = c("AMR", "AFR", "EAS")
plot_auc = rbind(rep(0.9, 5), rep(0.7, 5), plot_auc)

pdf(paste0(output_path, "AUC_radar.pdf"), width = 8, height = 8)
radarchart(plot_auc, axistype = 1 , maxmin = TRUE,
           #custom polygon
           pcol = colors_border, pfcol = colors_in, plwd = 3, plty = 1,
           #custom the grid
           cglcol = "grey", cglty = 1, axislabcol = "black", 
           caxislabels = seq(0.7, 0.9, 0.05), cglwd = 0.8,
           #custom labels
           vlcex = 0.9)
legend(x = 0.8, y = 1, legend = rownames(plot_auc[-c(1,2),]), bty = "n", 
       pch = 20 , col = colors_in , text.col = "black", cex = 1, pt.cex = 2)
dev.off()
```

# Part 3. Shared genes
```{r}
AMR_gene = read.table(file = paste0(output_path, "interpretation/amr_genes_info.txt"), 
                      header = T, sep = "\t", fill = T)
AMR_gene_lst = AMR_gene %>% select(symbol) %>% unique() %>% mutate(AMR_specific = 1)
AFR_gene = read.table(file = paste0(output_path, "interpretation/afr_genes_info.txt"), 
                      header = T, sep = "\t", fill = T)
AFR_gene_lst = AFR_gene %>% select(symbol) %>% unique() %>% mutate(AFR_specific = 1)
EAS_gene = read.table(file = paste0(output_path, "interpretation/eas_genes_info.txt"), 
                      header = T, sep = "\t", fill = T)
EAS_gene_lst = EAS_gene %>% select(symbol) %>% unique() %>% mutate(EAS_specific = 1)

genes_df = AMR_gene_lst %>% full_join(AFR_gene_lst) %>% full_join(EAS_gene_lst) %>% 
  mutate(AMR_specific = as.numeric(AMR_specific),
         AFR_specific = as.numeric(AFR_specific),
         EAS_specific = as.numeric(EAS_specific)) 
# Replace NAs with 0
genes_df[is.na(genes_df)] = 0
genes_df_combined = genes_df %>% unique()
save(genes_df_combined, file = paste0(output_path, "interpretation/genes_df_combined.rda"))
```

```{r}
pdf(paste0(output_path, "upset_shared_genes_0615.pdf"), width = 8, height = 5)
upset(genes_df_combined, sets = c("AMR_specific", "AFR_specific", "EAS_specific"), 
      sets.bar.color = "#56B4E9",
      order.by = "freq", empty.intersections = "on")
dev.off()
```

