---
title: "Sup3_EAS_analysis"
author: "Joy_Fu"
date: "2023-12-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
rm(list = ls())
# lapply(paste('package:', names(sessionInfo()$otherPkgs), sep = ""),
#        detach, character.only = TRUE, unload = TRUE)
pacman::p_load(tidyverse, h2o, caret, pROC, forestplot)
code_path = "/Users/Mingzhou/Desktop/Projects/Dementia-prediction/code/"
raw_data_path = "/Users/Mingzhou/Desktop/Projects/Dementia-prediction/data/"
output_path = "/Users/Mingzhou/Desktop/Projects/Dementia-prediction/output/"
# Source in useful functions
source("/Users/Mingzhou/Desktop/Projects/Dementia-prediction/code/functions.R")
# Read in SNP.id data
ids_folder = paste0(raw_data_path, "modeling/snp_ids") 
ids_files = list.files(ids_folder, pattern = ".rda$")
for (i in ids_files) {
  load(paste0(raw_data_path, 'modeling/snp_ids/', i))
}
```

# Part 1. Modeling
We ran bootstrapping (x1000) to get PRS model results.
```{r}
# source(paste0(code_path, "boot_PRS.R"))
# load in results
# load(file = paste0(raw_data_path, "modeling/EAS/PRS_bootstrap_full.rda"))
# dim(PRS_bootstrap_full) # dim = (21000,30)
# hist(PRS_bootstrap_full$AUCPR)
# There are some null results (AUCPR = 0.25 & AUC = 0.5). We decide to exclude 
# these results and make to full 1000 iterations
# exclude_boot_id = PRS_bootstrap_full %>% 
#   filter(AUCPR == 0.25 & AUC == 0.5) %>% pull(bootstrap) %>% unique()
# length(exclude_boot_id) # 32
# PRS_bootstrap_filter = PRS_bootstrap_full %>% 
#   filter(bootstrap %!in% exclude_boot_id)
# dim(PRS_bootstrap_filter) # dim = (20328,30)
# rerun the bootstrapping for N = 32 times
# load(file = paste0(raw_data_path, "modeling/EAS/PRS_bootstrap_full_add.rda"))
# exclude_boot_id = PRS_bootstrap_full %>% 
#   filter(AUCPR == 0.25 & AUC == 0.5) %>% pull(bootstrap) %>% unique()
# PRS_bootstrap_add1 = PRS_bootstrap_full %>% 
#   filter(bootstrap %!in% exclude_boot_id)
# load(file = paste0(raw_data_path, "modeling/EAS/PRS_bootstrap_full_add2.rda"))
# # combine together
# PRS_bootstrap_final = rbind(PRS_bootstrap_filter, PRS_bootstrap_add1,
#                             PRS_bootstrap_full)
# dim(PRS_bootstrap_final) # dim = (21000,30)
# hist(PRS_bootstrap_final$AUCPR)
# PRS_bootstrap_full = PRS_bootstrap_final
# dim(PRS_bootstrap_full) # dim = (21000,30)
# save(PRS_bootstrap_full, 
#      file = paste0(raw_data_path, "modeling/EAS/PRS_bootstrap_full_mod.rda"))
```

```{r}
load(file = paste0(raw_data_path, "modeling/EAS/PRS_bootstrap_full_mod.rda"))
na_counts = PRS_bootstrap_full %>% unique() %>%
  summarise(across(everything(), ~sum(is.na(.)))) # no NAs
```

We ran bootstrapping (x1000) to get SNP model results.
```{r}
# h2o.shutdown(prompt = F)
# h2o.init(nthreads = -1)
# Source in code (run background)
# source(paste0(code_path, "boot_SNP.R"))
# load in results
# load(file = paste0(raw_data_path, "modeling/EAS/SNP_bootstrap_full_150.rda"))
# dim(SNP_bootstrap_full)[1]/8
# dim(SNP_bootstrap_full) # dim = (8000,30)

# save(SNP_bootstrap_full, file = paste0(raw_data_path, "modeling/AMR/SNP_bootstrap_full.rda"))
# exclude_boot_id = SNP_bootstrap_full %>% 
#   filter(AUCPR == 0.25 & AUC == 0.5) %>% pull(bootstrap) %>% unique()
# length(exclude_boot_id) # 38
# SNP_bootstrap_filter = SNP_bootstrap_full %>% 
#   filter(bootstrap %!in% exclude_boot_id)
# dim(SNP_bootstrap_filter) # dim = (8000,30)
# hist(SNP_bootstrap_filter$AUCPR)
# SNP_bootstrap_full = SNP_bootstrap_filter
# dim(SNP_bootstrap_full) # dim = (8000,30)
# save(SNP_bootstrap_full, 
#      file = paste0(raw_data_path, "modeling/EAS/SNP_bootstrap_full_mod.rda"))
```


```{r}
load(file = paste0(raw_data_path, "modeling/EAS/SNP_bootstrap_full_mod.rda"))
dim(SNP_bootstrap_full) # dim = (8000,30)
na_counts = SNP_bootstrap_full %>% unique() %>%
  summarise(across(everything(), ~sum(is.na(.)))) # no NAs
```


## 1. Summary table
```{r}
# Specify the desired order of the character column
desired_order = c("e4count", "PRS.EUR.indsig", "PRS.EUR.map", "PRS.AFR.indsig", 
                  "PRS.AFR.map", "PRS.trans.indsig", "PRS.trans.map",
                  "PRS.AD.indsig.combine", "PRS.AD.map.combine", 
                  "PRS.neuro.indsig.combine", "PRS.neuro.map.combine",
                  "SNP.AD.indsig", "SNP.AD.map", "SNP.all.indsig",
                  "SNP.all.map")
```

```{r}
prs_summary_tbl = PRS_bootstrap_full %>% 
  select(AUCPR, AUC, f1, accuracy, precision, recall, specificity, 
         mark, bootstrap) %>% group_by(mark) %>% 
  summarise(mean_aucpr = mean(AUCPR), lower_aucpr = quantile(AUCPR, 0.025), 
            upper_aucpr = quantile(AUCPR, 0.975), mean_auc = mean(AUC), 
            lower_auc = quantile(AUC, 0.025), upper_auc = quantile(AUC, 0.975),
            mean_f1 = mean(f1), lower_f1 = quantile(f1, 0.025), 
            upper_f1 = quantile(f1, 0.975), mean_accuracy = mean(accuracy), 
            lower_accuracy = quantile(accuracy, 0.025), 
            upper_accuracy = quantile(accuracy, 0.975),
            mean_precision = mean(precision),
            lower_precision = quantile(precision, 0.025), 
            upper_precision = quantile(precision, 0.975),
            mean_recall = mean(recall), 
            lower_recall = quantile(recall, 0.025),
            upper_recall = quantile(recall, 0.975),
            mean_specificity = mean(specificity),
            lower_specificity = quantile(specificity, 0.025),
            upper_specificity = quantile(specificity, 0.975)) %>%
  mutate(AUCPR_stats = paste0(round(mean_aucpr, 3), " (", 
                 round(lower_aucpr, 3), ", ", round(upper_aucpr, 3), ")"),
         AUC_stats = paste0(round(mean_auc, 3), " (", 
                 round(lower_auc, 3), ", ", round(upper_auc, 3), ")"),
         f1_stats = paste0(round(mean_f1, 3), " (", 
                 round(lower_f1, 3), ", ", round(upper_f1, 3), ")"),
         accuracy_stats = paste0(round(mean_accuracy, 3), " (", 
                 round(lower_accuracy, 3), ", ", round(upper_accuracy, 3), ")"),
         precision_stats = paste0(round(mean_precision, 3), " (",
                 round(lower_precision, 3), ", ", 
                 round(upper_precision, 3), ")"),
         recall_stats = paste0(round(mean_recall, 3), " (",
                 round(lower_recall, 3), ", ", round(upper_recall, 3), ")"),
         specificity_stats = paste0(round(mean_specificity, 3), " (",
                 round(lower_specificity, 3), ", ", 
                 round(upper_specificity, 3), ")")) %>%
  select(mark, AUCPR_stats, AUC_stats, f1_stats, accuracy_stats, precision_stats, 
         recall_stats, specificity_stats) 

snp_summary_tbl = SNP_bootstrap_full %>% 
  select(AUCPR, AUC, f1, accuracy, precision, recall, specificity, 
         mark, bootstrap) %>% group_by(mark) %>% 
  summarise(mean_AUCPR = mean(AUCPR), lower_AUCPR = quantile(AUCPR, 0.025), 
            upper_AUCPR = quantile(AUCPR, 0.975), mean_AUC = mean(AUC), 
            lower_AUC = quantile(AUC, 0.025), upper_AUC = quantile(AUC, 0.975),
            mean_f1 = mean(f1), lower_f1 = quantile(f1, 0.025), 
            upper_f1 = quantile(f1, 0.975), mean_accuracy = mean(accuracy), 
            lower_accuracy = quantile(accuracy, 0.025), 
            upper_accuracy = quantile(accuracy, 0.975),
            mean_precision = mean(precision),
            lower_precision = quantile(precision, 0.025), 
            upper_precision = quantile(precision, 0.975),
            mean_recall = mean(recall), 
            lower_recall = quantile(recall, 0.025),
            upper_recall = quantile(recall, 0.975),
            mean_specificity = mean(specificity),
            lower_specificity = quantile(specificity, 0.025),
            upper_specificity = quantile(specificity, 0.975)) %>%
  mutate(AUCPR_stats = paste0(round(mean_AUCPR, 3), " (", 
                 round(lower_AUCPR, 3), ", ", round(upper_AUCPR, 3), ")"),
         AUC_stats = paste0(round(mean_AUC, 3), " (", 
                 round(lower_AUC, 3), ", ", round(upper_AUC, 3), ")"),
         f1_stats = paste0(round(mean_f1, 3), " (", 
                 round(lower_f1, 3), ", ", round(upper_f1, 3), ")"),
         accuracy_stats = paste0(round(mean_accuracy, 3), " (", 
                 round(lower_accuracy, 3), ", ", round(upper_accuracy, 3), ")"),
         precision_stats = paste0(round(mean_precision, 3), " (",
                 round(lower_precision, 3), ", ", 
                 round(upper_precision, 3), ")"),
         recall_stats = paste0(round(mean_recall, 3), " (",
                 round(lower_recall, 3), ", ", round(upper_recall, 3), ")"),
         specificity_stats = paste0(round(mean_specificity, 3), " (",
                 round(lower_specificity, 3), ", ", 
                 round(upper_specificity, 3), ")")) %>%
  select(mark, AUCPR_stats, AUC_stats, f1_stats, accuracy_stats, precision_stats, 
         recall_stats, specificity_stats)
```

```{r}
EAS_summary_tbl = rbind(prs_summary_tbl, snp_summary_tbl) %>% 
  filter(mark %in% desired_order) %>% 
  arrange(factor(mark, levels = desired_order))
# output to csv
write.csv(EAS_summary_tbl, 
          paste0(output_path, "model_stats/EAS_summary_tbl.csv") ,
          row.names = FALSE)
```

## 2. P-value calculation
```{r}
PRS_bootstrap_update = PRS_bootstrap_full %>% select(-bootstrap) 
PRS_bootstrap_update$bootstrap = rep(seq(1, 1000), each = 21)

SNP_bootstrap_update = SNP_bootstrap_full %>% select(-bootstrap)
SNP_bootstrap_update$bootstrap = rep(seq(1, 1000), each = 8)

combine_summary = rbind(PRS_bootstrap_update, SNP_bootstrap_update) 
dim(combine_summary) # dim = (29000, 30)

prs_columns = c("PRS.EUR.indsig", "PRS.EUR.map", "PRS.AFR.indsig", 
                "PRS.AFR.map", "PRS.trans.indsig", "PRS.trans.map",
                "PRS.AD.indsig.combine", "PRS.AD.map.combine",
                "PRS.neuro.indsig.combine", "PRS.neuro.map.combine")
snp_columns = c("SNP.AD.indsig", "SNP.AD.map", "SNP.all.indsig",
                "SNP.all.map")
aucpr_p = combine_summary %>%  
  select(mark, bootstrap, AUCPR) %>%
  pivot_wider(names_from = mark, values_from = AUCPR)
aucpr_p$max_prs = pmap_dbl(aucpr_p[prs_columns], max)
aucpr_p$max_snp = pmap_dbl(aucpr_p[snp_columns], max)
aucpr_p_summary = aucpr_p %>% 
  select(bootstrap, e4count, max_prs, max_snp, SNP.all.map) %>%
  mutate(prs_p = if_else(max_prs < SNP.all.map, 1, 0),
         e4count_p = if_else(e4count < SNP.all.map, 1, 0),
         map_is_max = if_else(max_snp <= SNP.all.map & max_prs < SNP.all.map, 1, 0)) 

table(aucpr_p_summary$e4count_p)[1]/1000                          
table(aucpr_p_summary$prs_p)[1]/1000
table(aucpr_p_summary$map_is_max)[1]/1000
```

```{r}
auc_p = combine_summary %>%  
  select(mark, bootstrap, AUC) %>%
  pivot_wider(names_from = mark, values_from = AUC)
auc_p$max_prs = pmap_dbl(auc_p[prs_columns], max)
auc_p$max_snp = pmap_dbl(auc_p[snp_columns], max)
auc_p_summary = auc_p %>% 
  select(bootstrap, e4count, max_prs, max_snp, SNP.all.map) %>%
  mutate(prs_p = if_else(max_prs < SNP.all.map, 1, 0),
         e4count_p = if_else(e4count < SNP.all.map, 1, 0),
         map_is_max = if_else(max_snp <= SNP.all.map & max_prs < SNP.all.map, 1, 0)) 

table(auc_p_summary$e4count_p)[1]/1000                          
table(auc_p_summary$prs_p)[1]/1000
table(auc_p_summary$map_is_max)[1]/1000
```


## 3. Selected SNPs
We ran bootstrapping (x1000) to get SNP map model (feature selected with 95%
confidence).
```{r}
load(file = paste0(raw_data_path, "modeling/EAS/snps_all_map_feature.rda"))
max_boot = max(snps_all_map_feature$bootstrap)
snps_map_summary = snps_all_map_feature %>% 
  group_by(variable) %>% 
  summarise(n = n(), mean_imp = mean(percentage), 
            lower_CI = quantile(percentage, 0.025),
            upper_CI = quantile(percentage, 0.975)) %>%
  arrange(desc(mean_imp)) %>% filter(n >= max_boot * 0.5) %>% 
  mutate(var_imp = paste0(round(mean_imp, 3), " (", 
                 round(lower_CI, 3), ", ", round(upper_CI, 3), ")")) %>% 
  select(variable, var_imp)
dim(snps_map_summary) # dim = (13,2)
```

```{r}
load(file = paste0(raw_data_path, "FUMA_outputs/overlap_fuma.rda"))
load(file = paste0(raw_data_path, "Interpretation/info_tbl/snp_info_full.rda"))
EAS_SNP_map = overlap_fuma %>% 
  filter(chr_pos_name %in% snps_map_summary$variable) %>% 
  select(chr_pos_name, rsID, chr_num, pos, phenotype) %>% 
  left_join(snp_info_full, by = c("rsID" = "rsID")) %>% unique() %>% 
  left_join(snps_map_summary, by = c("chr_pos_name" = "variable")) %>% 
  arrange(factor(chr_pos_name, levels = snps_map_summary$variable)) %>% 
  select(var_imp, rsID, chr_num, pos, CADD, nearestGene, dist, func, posMapFilt, 
         eqtlMapFilt, ciMapFilt, phenotype) %>% mutate(mark = "x") %>% 
  pivot_wider(names_from = phenotype, values_from = mark) 
dim(EAS_SNP_map) # dim = (13,17)
write.table(EAS_SNP_map, 
            file = paste0(output_path, "interpretation/EAS_SNP_map.txt"),
            sep = "\t", quote = F, row.names = F, col.names = T)
```

# Part 2. Interpretations
## 1. Data preparation
```{r}
load(file = paste0(raw_data_path, "Interpretation/info_tbl/gene_info_full.rda"))
load(file = paste0(raw_data_path, "Interpretation/info_tbl/snp_info_combine.rda"))
# Read in all eqtl/ci data
source("/Users/Mingzhou/Desktop/Projects/Dementia-prediction/code/read_FUMA.R")
gene_info_short = gene_info_full %>% 
  select(ensg, symbol, chr, start, end, type) %>% unique()

snps_EAS_map = read.table(file = paste0(output_path, "interpretation/EAS_SNP_map.txt"), 
                          sep = "\t", header = T, stringsAsFactors = F)
snps_EAS_map$ancestry = "EAS"
snps_EAS_map$STROKE = NA
```

## 2. Mapped genes
```{r}
pos_map_genes = snps_EAS_map %>% group_by(nearestGene) %>% 
  summarise(n_pos = n()) %>% select(nearestGene) %>% unique() %>% 
  mutate(positional = "Yes") %>% dplyr::rename("symbol" = "nearestGene")
```

```{r}
eqtl_map_pre = snps_EAS_map %>% filter(eqtlMapFilt == 1) %>% 
  left_join(snp_info_combine) %>% 
  select(uniqID, rsID, AD_EUR, AD_AFR, AD_trans, LBD, PD, PSP, LBD, STROKE)

eqtl_AD_EUR_map = eqtl_map_pre %>% filter(AD_EUR == "x") %>% left_join(eqtl_EUR)
eqtl_LBD_map = eqtl_map_pre %>% filter(LBD == "x") %>% left_join(eqtl_LBD)
eqtl_PD_map = eqtl_map_pre %>% filter(PD == "x") %>% left_join(eqtl_PD)
eqtl_PSP_map = eqtl_map_pre %>% filter(PSP == "x") %>% left_join(eqtl_PSP)

eqtl_map = rbind(eqtl_AD_EUR_map, eqtl_LBD_map, eqtl_PD_map, eqtl_PSP_map) %>% unique()
eqtl_map_genes = eqtl_map %>% select(symbol, alignedDirection) %>% 
  mutate(eqtl_pre = "Yes",
         eqtl = paste0(eqtl_pre, " (", alignedDirection, ")")) %>% 
  select(symbol, eqtl) %>% unique()
```

```{r}
ci_map_pre = snps_EAS_map %>% filter(ciMapFilt == 1)

ci_AFR_rsid = ci_map_pre %>% filter(AD_AFR == "x") %>% pull(rsID)
ci_AFR_genes = AD_AFR_ci %>% 
  filter(sapply(strsplit(SNPs, ";"), 
                function(x) any(x %in% ci_AFR_rsid))) %>% 
  select(genes) %>% drop_na() %>% unique()
ci_trans_rsid = ci_map_pre %>% filter(AD_trans == "x") %>% pull(rsID)
ci_trans_genes = AD_trans_ci %>% 
  filter(sapply(strsplit(SNPs, ";"), 
                function(x) any(x %in% ci_trans_rsid))) %>% 
  select(genes) %>% drop_na() %>% unique()
ci_PSP_rsid = ci_map_pre %>% filter(PSP == "x") %>% pull(rsID)
ci_PSP_genes = PSP_ci %>% 
  filter(sapply(strsplit(SNPs, ";"), 
                function(x) any(x %in% ci_PSP_rsid))) %>% 
  select(genes) %>% drop_na() %>% unique()
ci_LBD_rsid = ci_map_pre %>% filter(LBD == "x") %>% pull(rsID)
ci_LBD_genes = LBD_ci %>% 
  filter(sapply(strsplit(SNPs, ";"), 
                function(x) any(x %in% ci_LBD_rsid))) %>% 
  select(genes) %>% drop_na() %>% unique()

ci_map_full = rbind(ci_AFR_genes, ci_trans_genes, 
                    ci_PSP_genes, ci_LBD_genes) %>% unique()
ci_map_genes = ci_map_full %>% 
  left_join(gene_info_short, by = c("genes" = "ensg")) %>% unique() %>% drop_na() %>% 
  select(symbol) %>% unique() %>% mutate(ci = "Yes") %>% 
  filter(symbol != "Y_RNA")
```

```{r}
# combine together
eas_genes_info = pos_map_genes %>% full_join(eqtl_map_genes) %>% 
  full_join(ci_map_genes) %>% 
  left_join(gene_info_short) %>% filter(!is.na(ensg)) %>% 
  replace_na(list(positional = "No", eqtl = "No", ci = "No")) %>% 
  arrange(chr, start)
write.table(eas_genes_info, 
            file = paste0(output_path, "interpretation/eas_genes_info.txt"),
            sep = "\t", quote = F, row.names = F, col.names = T)
```
